### PR TITLE
Create panicReasons.hpp

### PR DESCRIPTION
**Pull request by SergeyMC9730**
yeah

### CODE REVIEW

**Comment by Yuhanun** [comment]
I can’t accept this.

you miss header guards, you’re writing C

switch to constexpr const char*, change your file + variable naming conventions (SCREAMING_SNAKE for constants, snake_case for file name) put it in a namespace and integrate it with the actual kernel panic()

**Comment by V01D-NULL** [comment]
I don't see a point in `const` error messages like these..

The reason I made panic accept a `const char *` rather than an int for the error code is because messages like "Driver error" or "Manually crashed" aren't very detailed.

What we could use is an error code in the future, however I fail to see a use in this.
Feel free to reply with a reason to keep it

**Comment by V01D-NULL** [comment]
@SergeyMC9730 https://github.com/SergeyMC9730/IcelyOS-Kernel
IcelyOS, really?
We cannot accept any PR's in the future if you change the core concepts that make up this project

This is Firefly OS, please accept it or write your own kernel.

Thanks

**Comment by SergeyMC9730** [comment]
> @SergeyMC9730 https://github.com/SergeyMC9730/IcelyOS-Kernel
> IcelyOS, really?
> We cannot accept any PR's in the future if you change the core concepts that make up this project
> 
> This is Firefly OS, please accept it or write your own kernel.
> 
> Thanks

Renamed

**Pull request closed without merging**
