### PR TITLE
Serial logger + log interface

### PR DESCRIPTION
**Pull request by lretq**

### CODE REVIEW

**Comment by lretq** [comment]
Also added -serial stdio in the scripts

**Comment by lretq** [comment]
@V01D-NULL added

**Comment by V01D-NULL** [comment]
Nice work, looks good to me.

One thing though, the logger namespace is a little overkill.

firefly::kernel::XyzLogger::log() is clear enough and doesn't require an additional logging namespace.

**Comment by lretq** [comment]
Not ready, something happend and I can't call log() successfully anymore, even after init etc

**Pull request merged**
